// Code generated by "shoot enum -json -text -file=enums.go"; DO NOT EDIT. (v0.3.2-beta.4)

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/lopolopen/shoot"
)

func _() {
	var x [1]struct{}
	_ = x[OrderStatusPending-0]
	_ = x[OrderStatusCompleted-1]
	_ = x[OrderStatusCanceled-2]
}

const _orderStatus_all = OrderStatusPending | OrderStatusCompleted | OrderStatusCanceled | 0

var _orderStatus_values = []OrderStatus{OrderStatusPending, OrderStatusCompleted, OrderStatusCanceled}
var _orderStatus_strings = []string{"Pending", "Completed", "Canceled"}
var _orderStatus_string_map = map[OrderStatus]string{
	OrderStatusPending:   "Pending",
	OrderStatusCompleted: "Completed",
	OrderStatusCanceled:  "Canceled",
}
var _orderStatus_value_map = map[string]OrderStatus{
	"Pending":   OrderStatusPending,
	"Completed": OrderStatusCompleted,
	"Canceled":  OrderStatusCanceled,
}

// String returns the string value of type OrderStatus
func (o OrderStatus) String() string {
	str, ok := _orderStatus_string_map[o]
	if ok {
		return str
	}
	if o < 0 || o > _orderStatus_all {
		return fmt.Sprintf("%d", o)
	}

	return fmt.Sprintf("%d", o)
}
func (o OrderStatus) Values() []OrderStatus {
	return _orderStatus_values
}
func (o OrderStatus) Strings() []string {
	return _orderStatus_strings
}
func (o OrderStatus) ValueMap() map[string]OrderStatus {
	return _orderStatus_value_map
}
func (o OrderStatus) StringMap() map[OrderStatus]string {
	return _orderStatus_string_map
}

// MarshalJSON implements the json.Marshaler interface for OrderStatus
func (o OrderStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for OrderStatus
func (o *OrderStatus) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ OrderStatus
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("OrderStatus enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[OrderStatus](s_); err != nil {
		return err
	}
	*o = v_
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for OrderStatus
func (o OrderStatus) MarshalText() ([]byte, error) {
	return []byte(o.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for OrderStatus
func (o *OrderStatus) UnmarshalText(text []byte) error {
	var v_ OrderStatus
	var err error
	if v_, err = shoot.ParseEnum[OrderStatus](string(text)); err != nil {
		return err
	}
	*o = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (o OrderStatus) ShootEnum() { /*noop*/ }
