// Code generated by "shoot new -getset -json -file=client.dto.go"; DO NOT EDIT.

package github

import "encoding/json"

// NewException constructs a new instance of type Exception
func NewException(message string, documentationUrl string, status string) *Exception {
	return &Exception{
		message:           message,
		documentation_url: documentationUrl,
		status:            status,
	}
}

// Message gets the value of field message
func (e *Exception) Message() string {
	return e.message
}

// DocumentationUrl gets the value of field documentation_url
func (e *Exception) DocumentationUrl() string {
	return e.documentation_url
}

// Status gets the value of field status
func (e *Exception) Status() string {
	return e.status
}

// SetMessage sets the value of field message
func (e *Exception) SetMessage(message_ string) {
	e.message = message_
}

// SetDocumentationUrl sets the value of field documentation_url
func (e *Exception) SetDocumentationUrl(documentation_url_ string) {
	e.documentation_url = documentation_url_
}

// SetStatus sets the value of field status
func (e *Exception) SetStatus(status_ string) {
	e.status = status_
}

type _Exception_marshal struct {
	Message          string `json:"message"`
	DocumentationUrl string `json:"documentation_url"`
	Status           string `json:"status"`
}
type _Exception_unmarshal struct {
	Message          string `json:"message"`
	DocumentationUrl string `json:"documentation_url"`
	Status           string `json:"status"`
}

// MarshalJSON serializes type Exception to json bytes
func (e Exception) MarshalJSON() ([]byte, error) {
	data := _Exception_marshal{
		Message:          e.Message(),
		DocumentationUrl: e.DocumentationUrl(),
		Status:           e.Status(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Exception
func (e *Exception) UnmarshalJSON(data []byte) error {
	var exception_ _Exception_unmarshal
	if err := json.Unmarshal(data, &exception_); err != nil {
		return err
	}
	e.SetMessage(exception_.Message)
	e.SetDocumentationUrl(exception_.DocumentationUrl)
	e.SetStatus(exception_.Status)

	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (e Exception) ShootNew() { /*noop*/ }

// NewOrg constructs a new instance of type Org
func NewOrg(id int64, nodeId string, login string, url string, reposUrl string, eventsUrl string, hooksUrl string, issuesUrl string, membersUrl string, publicMembersUrl string, avatarUrl string, description string) *Org {
	return &Org{
		id:                 id,
		node_id:            nodeId,
		login:              login,
		url:                url,
		repos_url:          reposUrl,
		events_url:         eventsUrl,
		hooks_url:          hooksUrl,
		issues_url:         issuesUrl,
		members_url:        membersUrl,
		public_members_url: publicMembersUrl,
		avatar_url:         avatarUrl,
		description:        description,
	}
}

// Id gets the value of field id
func (o *Org) Id() int64 {
	return o.id
}

// NodeId gets the value of field node_id
func (o *Org) NodeId() string {
	return o.node_id
}

// Login gets the value of field login
func (o *Org) Login() string {
	return o.login
}

// Url gets the value of field url
func (o *Org) Url() string {
	return o.url
}

// ReposUrl gets the value of field repos_url
func (o *Org) ReposUrl() string {
	return o.repos_url
}

// EventsUrl gets the value of field events_url
func (o *Org) EventsUrl() string {
	return o.events_url
}

// HooksUrl gets the value of field hooks_url
func (o *Org) HooksUrl() string {
	return o.hooks_url
}

// IssuesUrl gets the value of field issues_url
func (o *Org) IssuesUrl() string {
	return o.issues_url
}

// MembersUrl gets the value of field members_url
func (o *Org) MembersUrl() string {
	return o.members_url
}

// PublicMembersUrl gets the value of field public_members_url
func (o *Org) PublicMembersUrl() string {
	return o.public_members_url
}

// AvatarUrl gets the value of field avatar_url
func (o *Org) AvatarUrl() string {
	return o.avatar_url
}

// Description gets the value of field description
func (o *Org) Description() string {
	return o.description
}

// SetId sets the value of field id
func (o *Org) SetId(id_ int64) {
	o.id = id_
}

// SetNodeId sets the value of field node_id
func (o *Org) SetNodeId(node_id_ string) {
	o.node_id = node_id_
}

// SetLogin sets the value of field login
func (o *Org) SetLogin(login_ string) {
	o.login = login_
}

// SetUrl sets the value of field url
func (o *Org) SetUrl(url_ string) {
	o.url = url_
}

// SetReposUrl sets the value of field repos_url
func (o *Org) SetReposUrl(repos_url_ string) {
	o.repos_url = repos_url_
}

// SetEventsUrl sets the value of field events_url
func (o *Org) SetEventsUrl(events_url_ string) {
	o.events_url = events_url_
}

// SetHooksUrl sets the value of field hooks_url
func (o *Org) SetHooksUrl(hooks_url_ string) {
	o.hooks_url = hooks_url_
}

// SetIssuesUrl sets the value of field issues_url
func (o *Org) SetIssuesUrl(issues_url_ string) {
	o.issues_url = issues_url_
}

// SetMembersUrl sets the value of field members_url
func (o *Org) SetMembersUrl(members_url_ string) {
	o.members_url = members_url_
}

// SetPublicMembersUrl sets the value of field public_members_url
func (o *Org) SetPublicMembersUrl(public_members_url_ string) {
	o.public_members_url = public_members_url_
}

// SetAvatarUrl sets the value of field avatar_url
func (o *Org) SetAvatarUrl(avatar_url_ string) {
	o.avatar_url = avatar_url_
}

// SetDescription sets the value of field description
func (o *Org) SetDescription(description_ string) {
	o.description = description_
}

type _Org_marshal struct {
	Id               int64  `json:"id"`
	NodeId           string `json:"node_id"`
	Login            string `json:"login"`
	Url              string `json:"url"`
	ReposUrl         string `json:"repos_url"`
	EventsUrl        string `json:"events_url"`
	HooksUrl         string `json:"hooks_url"`
	IssuesUrl        string `json:"issues_url"`
	MembersUrl       string `json:"members_url"`
	PublicMembersUrl string `json:"public_members_url"`
	AvatarUrl        string `json:"avatar_url"`
	Description      string `json:"description"`
}
type _Org_unmarshal struct {
	Id               int64  `json:"id"`
	NodeId           string `json:"node_id"`
	Login            string `json:"login"`
	Url              string `json:"url"`
	ReposUrl         string `json:"repos_url"`
	EventsUrl        string `json:"events_url"`
	HooksUrl         string `json:"hooks_url"`
	IssuesUrl        string `json:"issues_url"`
	MembersUrl       string `json:"members_url"`
	PublicMembersUrl string `json:"public_members_url"`
	AvatarUrl        string `json:"avatar_url"`
	Description      string `json:"description"`
}

// MarshalJSON serializes type Org to json bytes
func (o Org) MarshalJSON() ([]byte, error) {
	data := _Org_marshal{
		Id:               o.Id(),
		NodeId:           o.NodeId(),
		Login:            o.Login(),
		Url:              o.Url(),
		ReposUrl:         o.ReposUrl(),
		EventsUrl:        o.EventsUrl(),
		HooksUrl:         o.HooksUrl(),
		IssuesUrl:        o.IssuesUrl(),
		MembersUrl:       o.MembersUrl(),
		PublicMembersUrl: o.PublicMembersUrl(),
		AvatarUrl:        o.AvatarUrl(),
		Description:      o.Description(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Org
func (o *Org) UnmarshalJSON(data []byte) error {
	var org_ _Org_unmarshal
	if err := json.Unmarshal(data, &org_); err != nil {
		return err
	}
	o.SetId(org_.Id)
	o.SetNodeId(org_.NodeId)
	o.SetLogin(org_.Login)
	o.SetUrl(org_.Url)
	o.SetReposUrl(org_.ReposUrl)
	o.SetEventsUrl(org_.EventsUrl)
	o.SetHooksUrl(org_.HooksUrl)
	o.SetIssuesUrl(org_.IssuesUrl)
	o.SetMembersUrl(org_.MembersUrl)
	o.SetPublicMembersUrl(org_.PublicMembersUrl)
	o.SetAvatarUrl(org_.AvatarUrl)
	o.SetDescription(org_.Description)

	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Org) ShootNew() { /*noop*/ }
