// Code generated by "shoot rest -type=Client"; DO NOT EDIT.

package github

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"time"

	"github.com/lopolopen/shoot"
)

type client struct {
	client *http.Client
	conf   *shoot.RestConf
}

func (c *client) ListOrgsForUser(per_page *int, page *int) ([]Org, *Exception, error) {
	path_ := "/user/orgs"

	url_, err := url.JoinPath(c.conf.BaseURL(), path_)
	if err != nil {
		return nil, nil, err
	}

	req_, err := http.NewRequest("GET", url_, nil)
	if err != nil {
		return nil, nil, err
	}

	query_ := req_.URL.Query()
	if per_page != nil {
		query_.Set("per_page", fmt.Sprintf("%v", *per_page))
	}
	if page != nil {
		query_.Set("page", fmt.Sprintf("%v", *page))
	}
	req_.URL.RawQuery = query_.Encode()

	req_.Header.Add("Accept", "application/vnd.github+json")
	req_.Header.Add("X-GitHub-Api-Version", "2022-11-28")

	resp_, err := c.client.Do(req_)
	if err != nil {
		return nil, nil, err
	}
	defer resp_.Body.Close()

	body_, _ := io.ReadAll(resp_.Body)

	if resp_.StatusCode >= 500 {
		err = fmt.Errorf("server error %d: %s", resp_.StatusCode, string(body_))
		return nil, nil, err
	}
	if resp_.StatusCode < 300 {
		var r_ []Org
		err = json.Unmarshal(body_, &r_)
		if err != nil {
			return nil, nil, err
		}
		return r_, nil, nil
	} else {
		var r_ Exception
		err = json.Unmarshal(body_, &r_)
		if err != nil {
			return nil, nil, err
		}
		return nil, &r_, nil
	}
}

// ConfigHTTPClient allows customization of the underlying http.Client.
func (c *client) ConfigHTTPClient(config func(*http.Client)) Client {
	config(c.client)
	return c
}

// ShootRest exists solely to fulfill the RestShooter interface contract.
func (c *client) ShootRest() { /*noop*/ }

func init() {
	shoot.Register(func(conf shoot.RestConf) Client {
		return &client{
			conf: &conf,
			client: &http.Client{
				Timeout:   time.Duration(conf.Timeout()) * time.Second,
				Transport: conf.BuildMiddleware(),
			},
		}
	})
}
