// Code generated by "shoot map -path=../../domain/model -alias=domain -type=*"; DO NOT EDIT. (v0.3.2-beta.4)

package dto

import domain "shoot-examples/shootmap/domain/model"

// ToDomain converts receiver to type domain.Order
func (o *Order) ToDomain() *domain.Order {
	if o == nil {
		return nil
	}
	order_ := new(domain.Order)
	order_.ID = o.ID
	order_.Amount = o.StringToDecimal(o.Amount)
	order_.Status = o.Status
	order_.OrderTime = o.StringToTime(o.OrderingTime)
	if o.Address != nil {
		order_.Address = *o.Address.ToDomain()
	}
	o.writeDomain(order_)
	return order_
}

// FromDomain reads from type domain.Order, then writes back to receiver and returns it
func (o *Order) FromDomain(order_ *domain.Order) *Order {
	if order_ == nil {
		return o
	}
	if o == nil {
		o = new(Order)
	}
	o.ID = order_.ID
	o.Amount = o.DecimalToString(order_.Amount)
	o.Status = order_.Status
	o.OrderingTime = o.TimeToString(order_.OrderTime)
	o.Address = new(OrderAddress).FromDomain(&order_.Address)
	o.readDomain(order_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.OrderAddress
func (o *OrderAddress) ToDomain() *domain.OrderAddress {
	if o == nil {
		return nil
	}
	orderAddress_ := new(domain.OrderAddress)
	orderAddress_.City = o.City
	orderAddress_.Street = o.Street
	orderAddress_.Room = o.RoomNum
	return orderAddress_
}

// FromDomain reads from type domain.OrderAddress, then writes back to receiver and returns it
func (o *OrderAddress) FromDomain(orderAddress_ *domain.OrderAddress) *OrderAddress {
	if orderAddress_ == nil {
		return o
	}
	if o == nil {
		o = new(OrderAddress)
	}
	o.City = orderAddress_.City
	o.Street = orderAddress_.Street
	o.RoomNum = orderAddress_.Room
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o OrderAddress) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.User
func (u *User) ToDomain() *domain.User {
	if u == nil {
		return nil
	}
	user_ := new(domain.User)
	user_.ID = u.ID
	user_.Email = u.Email
	if u.Addresses != nil {
		user_.AddressList = make([]*domain.UserAddress, len(u.Addresses))
		for _i, _x := range u.Addresses {
			user_.AddressList[_i] = _x.ToDomain()
		}
	}
	u.toDomain(user_)
	return user_
}

// FromDomain reads from type domain.User, then writes back to receiver and returns it
func (u *User) FromDomain(user_ *domain.User) *User {
	if user_ == nil {
		return u
	}
	if u == nil {
		u = new(User)
	}
	u.ID = user_.ID
	u.Email = user_.Email
	if user_.AddressList != nil {
		u.Addresses = make([]UserAddress, len(user_.AddressList))
		for _i, _x := range user_.AddressList {
			u.Addresses[_i] = *new(UserAddress).FromDomain(_x)
		}
	}
	u.fromDomain(*user_)
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.UserAddress
func (u *UserAddress) ToDomain() *domain.UserAddress {
	if u == nil {
		return nil
	}
	userAddress_ := new(domain.UserAddress)
	userAddress_.ID = u.ID
	userAddress_.City = u.City
	userAddress_.Street = u.Street
	userAddress_.Room = u.Room
	userAddress_.Tag = u.Tag
	userAddress_.IsDefault = u.IsDefault
	userAddress_.OwnerID = u.UserID
	return userAddress_
}

// FromDomain reads from type domain.UserAddress, then writes back to receiver and returns it
func (u *UserAddress) FromDomain(userAddress_ *domain.UserAddress) *UserAddress {
	if userAddress_ == nil {
		return u
	}
	if u == nil {
		u = new(UserAddress)
	}
	u.ID = userAddress_.ID
	u.City = userAddress_.City
	u.Street = userAddress_.Street
	u.Room = userAddress_.Room
	u.Tag = userAddress_.Tag
	u.IsDefault = userAddress_.IsDefault
	u.UserID = userAddress_.OwnerID
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u UserAddress) ShootMap() { /*noop*/ }
