// Code generated by "shoot map -path=../../domain/qpo -type=*"; DO NOT EDIT. (v0.4.2-beta.2)

package dto

import "shoot-examples/shootmap/domain/qpo"

// ToQpo converts receiver to type qpo.Pagination
func (p *Pagination) ToQpo() *qpo.Pagination {
	if p == nil {
		return nil
	}
	pagination_ := new(qpo.Pagination)
	pagination_.Page = p.Page
	pagination_.PerPage = p.PerPage
	return pagination_
}

// FromQpo reads from type qpo.Pagination, then writes back to receiver and returns it
func (p *Pagination) FromQpo(pagination_ *qpo.Pagination) *Pagination {
	if pagination_ == nil {
		return nil
	}
	if p == nil {
		p = new(Pagination)
	}
	p.Page = pagination_.Page
	p.PerPage = pagination_.PerPage
	return p
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (p Pagination) ShootMap() { /*noop*/ }
